version: "3" ###

services:
  backend: #
    build:
      context: ./back
      args:
        - NODE_ENV=development # make sure dev depencies are installed (e.g. nodemon)
    command: ../node_modules/.bin/nodemon server.js 
    volumes:
      - ./back:/app
    ports:
      - "4000:3000" #
    environment:
      - NODE_ENV=development
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=example-db
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  

    
